### ISSUE TITLE
[REQUEST] - Possibility to create merchants and shops

### ISSUE THREAD

**Issue by gubacelar** [fantasycalendar/FoundryVTT-ItemPiles#107]
The module is very easy and intuitive and already adds great mechanics to the game.
I would like to suggest the possibility of creating merchants and shops. Players could interact with the token and buy the items by spending their money.

Items could be populated through a table.

I know there are already modules similar to what I'm asking for, but the Item Pile interface is much better and more intuitive.

**Comment by Haxxer** [comment]
I'm currently in the process of developing an extensive mercantile system (see #108) , which will be able to handle all sorts of scenarios:

- Accessing merchant through the actors directory (if user has at least limited permissions to view the actor)
- Accessing merchant only on certain scenes
    - For city scenes, you can set the shop's interaction distance to infinite and the players will be able to double click on their token in the city
    - For map scenes, you can set the shop's interaction distance so that the players have to physically walk to the shop with their tokens
- Comprehensive currency systems where you can configure certain merchants only accept a certain form of payment, be that a currency on the character sheet (like gold, silver, etc) or another attribute, such as health
- Support for item-based currencies where one merchant only accepts a certain item in exchange for another item, so that players have to find ingredients or other items in order to purchase it

If you'd like to support the development, please consider donating so that I can fuel my coding binges with copious amounts of caffeine!

https://ko-fi.com/fantasycomputerworks
