### ISSUE TITLE
[BUG] Windows get blurry after moving them

### ISSUE THREAD

**Issue by gsterling** [fantasycalendar/FoundryVTT-ItemPiles#177]
**Describe the bug**
When moving ItemPiles windows, they get blurry, which gives (at least) me a slight headache, since my eyes try to focus the window, which they can't.

**To Reproduce**
1. Open an item pile
2. See it being sharp
3. Wiggle the window around a bit (this also lags a little bit, but it's not really distracting)
4. See the window now being blurry

**Expected behavior**
The window should always look as sharp as when it was first opened.

**Screenshots**
Sharp:
![image](https://user-images.githubusercontent.com/58980630/197786238-c0ddc721-e5f7-422a-954e-05feb6de93bc.png)

Blurry:
![image](https://user-images.githubusercontent.com/58980630/197786272-81c9841f-47ca-41fb-a546-4e8f45c17906.png)

**Setup:**
 - Foundry Version: 10.288
 - System Version: Splittermond 0.9.7
 - Item Piles Version: 2.2.10
 - Browser & version: Chromium 106.0.5249.119

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

(I disabled all other modules)

**Comment by JustinCamden** [comment]
Out of curiosity, 

1. Does this occur with firefox?
2. Do you have a zoom level other than 100%?

**Comment by gsterling** [comment]
> Out of curiosity,
> 
>     1. Does this occur with Firefox?

No. But performance-wise regarding foundry firefox is not a good alternative, although it's my daily driver.
 
>     2. Do you have a browser zoom level other than 100%?
I did! And I haven't noticed, because it was only 110%. This makes the problem better, but it's still there, although I likely wouldn't have noticed it.

![image](https://user-images.githubusercontent.com/58980630/197970963-a753eed1-a109-49cd-9ff3-90b7c4ba73d2.png)

>     3. What OS are you running?

Arch Linux with Wayland as a compositor.

>     4. What is the resolution of your monitor?

4k, but I also tried with 1080p on the same monitor.

**Comment by typhonrt** [comment]
Hi @gsterling. I'm the developer of the underlying UI library that Item Piles uses. This is an uncommon problem reported, but you are the 2nd to have a reproducible set of hardware. The other case is reported on Windows 11, but also Chrome browser. Quite likely this is an issue w/ the Chrome rendering engine / compositor in particular that is misbehaving; IE you don't see the issue in Firefox. 

The underlying UI library uses standard CSS / JS, but is optimized rendering by using `transform: matrix3d(...)` for UI window movement. This promotes the app / UI window element to being hardware accelerated and likely a combination between your monitor resolution and possibly various OS / browser scaling settings causes the Chrome renderer / compositor to misbehave. 

Can you tell me your monitor make / model / resolution? The other reporter has a UHD monitor at 2560x1440. 

I'm trying to collect as much information about system specs for those affected by this external / browser issue to report data to the Chromium / Chrome bug tracker. Chrome while very good has had `blurry text` issues for many years.

Next week I'm going to put together some isolated test cases that you can try out so that I can submit the system specifications + a minimal test case to the Chromium dev team. 

Thanks for helping. It's good that you have a different OS than Windows, so that possibly removes OS scaling aspects from the likely culprits, but other aspects such as monitor resolution could be correlated.

**Comment by gsterling** [comment]
> Can you tell me your monitor make / model / resolution? The other reporter has a UHD monitor at 2560x1440.

Samsung UHD Monitor U28E590DSL at 3840x2160, but this also happens when running the monitor at 1920x1080. Connected with displayport.

I am using a Sapphire RX 590 Nitro+ Special Edition Radeon RX 590 8 GB GDDR5 with the latest `amdgpu` driver for Arch Linux.

> Next week I'm going to put together some isolated test cases that you can try out so that I can submit the system specifications + a minimal test case to the Chromium dev team, so that this data can be triaged and either added to an existing bug or file a new bug / issue w/ Chrome.

Yes, send anything you want me to test.

> Thanks for helping. It's good that you have a different OS than Windows

I think so, too :laughing:

**Comment by typhonrt** [comment]
@gsterling It's definitely interesting that the first correlation is a UHD monitor even though the resolutions are different. I'll be following up with you next week once I get some isolated test cases together. Probably as late as mid-next week. 

Thanks for taking the time to respond. I run a tight ship in code quality and this is the only external issue affecting my UI library right now.  There is a thread on my Discord server where we are discussing this issue and it seems like you might be technically savvy. It could be easier to chat there if that makes sense for you: 
https://discord.gg/mnbgN8f
Under the `Development` -> `#typhonjs-runtime` -> `DPI scaling issues - Chrome` thread.

**Comment by typhonrt** [comment]
Hi @gsterling... I have the first basic testcase created. I am using the Svelte REPL. My UI library does use Svelte, but it's the CSS / styles used w/ the browser that is causing Chrome to freak out. If you drag the mock app window does the text get blurry in the content areas? There is more things to potentially setup for testing and this is a basic test right now, but good to test if it gets blurry now. 

https://svelte.dev/repl/2f8ab0453ee34e52bff869e7c9d769d8?version=3.52.0

I'm going to have to come back to this testing effort next week, but at least there is an initial test above to try out for now and report back. Thanks for your help.

**Comment by gsterling** [comment]
While trying to create new screenshots I refreshed the site and now I only get
![image](https://user-images.githubusercontent.com/58980630/198011518-8a97f66c-af20-4fa1-b00f-672c8c6bf456.png)

**Comment by gsterling** [comment]
It is only noticable with 110% zoom. It looks better in your test app than it does in foundry. I assume it's because of the font used. Can you change it to a serif font?

Default (110%):
![image](https://user-images.githubusercontent.com/58980630/198012000-aafec267-fdf4-4762-88d4-d6d937f1572e.png)

Moved:
![image](https://user-images.githubusercontent.com/58980630/198012100-2a04235d-cc31-464d-baef-70a35cdd0b54.png)

Moved to a spot where it looks a little bit less blurry:
![image](https://user-images.githubusercontent.com/58980630/198012200-97dcad60-195a-4b99-a660-374fa4729a9f.png)

So it heavily depends on where the window is positioned.

For comparison, a moved window with 100% zoom:
![image](https://user-images.githubusercontent.com/58980630/198012853-4b879f8a-4568-457c-b25b-7bcc2f0b3617.png)


BTW: Chromium uses around 100% CPU equivilant of a single core (spread across 3 cores), when moving the windows.

**Comment by typhonrt** [comment]
@gsterling Apologies about the errors.. I was updating the demo to add the z-index test / value. So we are definitely onto something as this is a very basic test case. Let me change a few more things. I added a new checkbox 'Enable will-change transform'. This will turn on and off the parameter that could be causing the issue w/ Chrome. I also made the text bold and serif font. If the blurry text appears without hitting any of those checkboxes on refresh / fresh load that is very good information to have. 

Regarding the window moving / CPU usage; I'm not really throttling any of the updates / mouse dragging and this is a basic test case. I wouldn't worry right now if that seems off.. On my setup CPU usage goes from 5% to 12% then drops back down when dragging is stopped.

**Comment by typhonrt** [comment]
@gsterling One more sanity check... I changed things around so that only the window initially on the right is affected by the `will-change` setting. 

So these symptoms do seem like this bug in Chrome: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1343711

Particularly the explanation in comment #4 seems to describe the symptom observed:
https://bugs.chromium.org/p/chromium/issues/detail?id=1343711#c4

Good news is that `will-change` can be dropped. It's just an optimization to tell the browser that transform changes a lot; the browser does promote eventually to the optimized path. Totally weird that this affects a small amount of users with particular setups.

Perhaps give the demo another try as it will be easier to see the difference between the will-change affected window.

**Comment by gsterling** [comment]
> Also if you could check in Foundry. Open up Item Piles and the Chrome dev tools / Elements. You can manually remove the `will-change: transform` from the inline styles by double clicking on the inline style. When looking at the element / app window in the dev tools you'll see a bottom app added to the body element like this: ![image](https://user-images.githubusercontent.com/311473/198098231-c5fbc71a-1dff-4b4a-b972-891e795fecd6.png)
> 
> Double click on the inline style and just edit out the `will-change: transform` and the idea is that the Item Piles app should then not be blurry.

This did the trick! It looks sharp now.

**Comment by typhonrt** [comment]
@gsterling Well thanks for the testing. I can indeed easily remove this CSS property. It's not necessary strictly; a nice to have, but of course it's a Chrome bug. As things go this will require a rebuild of all packages w/ the latest UI library release, so hopefully things get updated in the coming couple of weeks.

**Comment by Haxxer** [comment]
@gsterling Does this still happen in the latest version of item piles?
