### ISSUE TITLE
[REQUEST] - Make tokens lootable to a single pile

### ISSUE THREAD

**Issue by CaosFR** [fantasycalendar/FoundryVTT-ItemPiles#179]
**Is your feature request related to a problem? Please describe.**
Hi, simple request for this beautifull module. When combat are finish I convert all tokens to loots with your macro "Make tokens lootable". After that my players rush to open all killed NPC. It's pretty cool, but it's a little chaos when they are 30 deads bodys.

**Describe the solution you'd like**
If possible I would like a single pile with all items and currency from multiples tokens.

**Describe alternatives you've considered**
This "pile" could be create automaticly from ennemis at the end of a fight or with multiple tokens selected with a macro.

**Additional context**
Thanks !

**Comment by p4535992** [comment]
This has been asked several times and by several people on discord, the solutions are many, the honeybadger with warpgate solution is probably the best https://github.com/trioderegion/fvtt-macros/blob/master/honeybadger-macros/tokens/single-loot-pile.js.

The problem is that people don't know how to use macros XD or are afraid of them, they just want the button...

If wasp agrees I can try to modify the honeybadger macro for the multisystem integration and add a button (somewhere you tell me where) to convert the selected tokens.

**Comment by CaosFR** [comment]
Thanks for the link and for your proposition of modify the macro.

**Comment by Haxxer** [comment]
Added with 3.1.0 as a part of `game.itempiles.API.combineItemPiles`
