### ISSUE TITLE
[REQUEST] - Option for item filters to be a whitelist

### ISSUE THREAD

**Issue by Nysterian** [fantasycalendar/FoundryVTT-ItemPiles#368]
The module currently has an option to "Override Item Filters", which acts as a blacklist for items that you don't want to be inserted into the item pile. This is great for when you want to stop certain items from entering the item pile in question.

However, I'm currently in a situation where I only want a very limited number of items to be allowed into the item pile... Using the filter like this would mean that I'd need to include exceptions for every single item in the game except the ones in question, and this sounds unnecessarily complicated, when there could simply be a different list, that acted the exact same way, but having it be a whitelist instead of a blacklist.

**Comment by freohr** [comment]
I'm also interested in this feature, since it would be very useful for filtering items in addition to the custom categories that can be configured by this module.

I'm not sure who to mention to get insight about how the module is supposed to work, so I'll have to tag @Haxxer (sorry about that).

I've looked around the code where the filtering happens (https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/96f51f1f7e00acb9df4ef30c0c03a843363b692c/src/helpers/pile-utilities.js#L318 from the latest master commit), and just reversing the condition for filtering enables white-listing instead of blacklisting.

However, I don't believe that simply switching the module to white-listing is a good thing (or even a practical one), so I have a few questions about how one could go and implement whitelisting in the module:

- Easiest would be to have an additional toggle for the entire Pile in the "Item Piles Filters Editor" to activate whitelisting for this pile specifically instead of blacklisting. It would need an additional boolean flag on the item, right besides the "overrideItemFilters" flag, and an additional check on the filtering function
- Hardest to implement would be for each filter to be either exclude or include, but this would requires a good deal of UI rewrite, to change the internal structure for the ItemPiles specific item flags and to change the filtering logic. But it would be far more flexible for the user in the end.

**Comment by adunis** [comment]
Hello, I implemented this feature in this way: 

If you put "!" before a path field, it will negate the filter. For example if you put a filter with path: "!name" and value "Iron", a Merchant will be able to buy and sell only items named 'Iron'

Pull Request: https://github.com/fantasycalendar/FoundryVTT-ItemPiles/pull/538

**Comment by Haxxer** [comment]
Added in 2.9.0
