### ISSUE TITLE
[BUG] - [Star Wars: Saga Edition] - Currency and cost is broken

### ISSUE THREAD

**Issue by cpadilla** [fantasycalendar/FoundryVTT-ItemPiles#466]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When creating an item pile or a merchant, the cost of items is always set to Free and cannot be changed by manually setting the price. The cost should be associated with the cost attribute of the item.

Also, when creating a merchant from an item pile and shopping with it using a player who has credits, the shop shows that the players credits is 0, which is incorrect.

**To Reproduce**

1. Create an item pile (notice the cost of the item is Free)
2. Convert the item pile into a merchant
3. Access the merchant via a player with credits
4. The merchant shows the players credits are 0

**Expected behavior**
The cost of items should be based on the cost attribute of the item and merchants should show the amount of credits a player has based on the credits on their character sheet.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/1704172/bc38e683-8720-4143-8893-5364733c7def)

**Setup:**

- Foundry Version: 11[e.g. 9.238]
- System Version: [Saga Edition](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition) v 0.7.11
- Item Piles Version: [e.g. 1.0.0]
- Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
The system may have updated and broken the item piles' settings for the system. I did not make the support for the system, because I don't play in that system, and there are like 30 supported systems, all created by people who help support item piles - if you wish to help fix it, you can ask in the discord channel on the main foundry server for help. This is its config:
<https://github.com/fantasycalendar/FoundryVTT-ItemPiles/blob/master/src/systems/sw5e.js>
