### ISSUE TITLE
[BUG] - [D&D 5e 3.3.1] - unable to set amount on containers at merchants

### ISSUE THREAD

**Issue by TheXeno30** [fantasycalendar/FoundryVTT-ItemPiles#673]
**I confirm the following:**
- [x ] I am on the latest version of Item Piles
- [x ] I have tried to clear my cache (Ctrl / Cmd + F5)
- [ x] I have checked the console for errors (F12 to open, Console tab)
- [x ] I have tried to reset Item Piles' system settings
- [ x] I have reproduced this bug with only item piles & its dependency modules enabled

**Describe the bug**
unable to set amount on containers at merchants.

**To Reproduce**
-

**Expected behavior**
Set an amount like any other item for sale

**Screenshots**
![image](https://github.com/user-attachments/assets/dce92372-72c4-4187-a57b-18b217714185)

**Setup**
- Foundry Version: 12.331
- System Version: D&D 5e 3.3.1
- Item Piles Version: 3.1.6
- Browser & version Google Chrome

**Comment by rsadamoresten** [comment]
The problem is that containers can contain other items - so if you have a saddlebag with 2x quantity that contains a specific item, say, a rope, that rope only exists in one of the saddlebags. But a saddlebag with 2x quantity means there are two containers that have the exact same item in it. See the problem? Hence, containers cannot have quantity.

**Comment by Haxxer** [comment]
@TheXeno30 see above

**Comment by Haxxer** [comment]
In fact, D&D5e ENFORCES a minimum and maximum quantity of 1:

https://github.com/foundryvtt/dnd5e/blob/release-4.0.4/module/data/item/container.mjs#L39
