### ISSUE TITLE
[REQUEST] - Add support for system specific information to be set on items when looted

### ISSUE THREAD

**Issue by krbz999** [fantasycalendar/FoundryVTT-ItemPiles#84]
**Describe the bug**
Specific to D&D5e. When looting a tool (possibly other item types too), the proficiency field is not changed. The normal behavior for tools is to change to match the actor's tool proficiency. I.e., if the actor is proficient with Potter's Tools and they add such a tool to their sheet, the item changes from Not Proficient to Proficient. This doesn't happen when looting from an item pile.

**To Reproduce**
1. Make an actor that is proficient with a specific tool.
2. Add such a tool to an item pile where it is set to Not Proficient.
3. Loot the tool from the item pile using the created actor.
4. Error: The item is not set as Proficient automatically.

**Expected behavior**
In step 4, the tool should be set as Proficient. This happens when dragging a tool onto the sheet manually.

**Setup:**
- Foundry Virtual Tabletop: Version 9.255
- Game System: dnd5e, 1.5.7
- Item Piles Version: 1.4.7

**Comment by Haxxer** [comment]
This is partially intended, as items created on actors via Foundry's function does not get this information on them, and as not all systems that Item Piles support, it would be nearly impossible for me to support individual system granularities. I'll make this ticket into an enhancement, rather than a bug, as this is expected behavior.
